### ISSUE TITLE
让实例可以正常关闭

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkitX/PNX-CLI#6]
### 现在的问题
通过[StartCommand.java#L136](https://github.com/PowerNukkitX/PNX-CLI/blob/a2b89ba30f79e52445a7b277f7dc7846d1bde500/src/main/java/cn/powernukkitx/cli/cmd/StartCommand.java#L136)可以发现，无论有无--restart参数，PNX-CLI都会执行`start()`

这显然不合理。

### 更改
在没有`--restart`时不自动重启实例，或者在`-r=false`时不自动重启实例。

**Comment by Superice666** [comment]
此问题无法复现，代码分析片面且错误
